services:
  jellych:
    #command: --addr :8080 --config /data/config --vods /data/vods
    image: ghcr.io/c2bw/jellych:latest
    restart: unless-stopped
    volumes:
      - config_volume:/data/config
      - vods_volume:/data/vods
    environment:
      - LOG_LEVEL=INFO
      - VOD_RETENTION_DAYS=30
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:?Set TWITCH_CLIENT_ID environment variable}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET:?Set TWITCH_CLIENT_SECRET environment variable}
      - SERVER_URL=${SERVER_URL:?Set SERVER_URL environment variable}
      - JELLYFIN_WEBHOOK_SECRET=${JELLYFIN_WEBHOOK_SECRET:?Set JELLYFIN_WEBHOOK_SECRET environment variable}
    ports:
      - 8080:8080
    #healthcheck:
    #  test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/health"]
    #  interval: 30s
    #  timeout: 3s
    #  start_period: 10s
    #  retries: 3
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "2.0"
    #      memory: 1000M
    #memswap_limit: 1050M

volumes:
  config_volume:
  vods_volume:
